### PR TITLE
Re-introduce duplicate symbol check

### PR DESCRIPTION
**Pull request by rvagg**
Originally in #1689 and was reverted in #1828, we decided in https://github.com/nodejs/node/pull/28647#issuecomment-511715968 it was "breaking" as far as Node was concerned.

Given the dependency chain to get to Node I'm not sure what to do about this. Is it enough to put a semver-major label on it? It's still likely to bubble up to Node 12 (and maybe 10) through their regular npm updates though. Is there a rule in place that would prevent certain versions of npm getting into Node 12? And how do we couple that with our moves to get to Python 3 support and the semver-major nature of them? Do we then prevent Node 12 from getting Python 3 support if we block a semver-major release of node-gyp getting back in to older versions of Node?

/cc @gabrielschulhof @bnoordhuis @nodejs/npm

### CODE REVIEW

**Comment by rvagg** [comment]
Unless someone thinks this is urgent I think we should punt this till 7.0.0 so we can focus on python 3 compat in 6.x.

**Comment by gabrielschulhof** [comment]
@rvagg I have no special reason to push for urgency. It would be good if it landed though, because, as it is, there might be all kinds of weird errors with equally weird solutions.

**Comment by cclauss** [comment]
Reading the output was superimpossible because of all the backslashes but at its root the test failure is caused by #1904

**Comment by rvagg** [comment]
green after rebase to master

**Comment by vweevers** [comment]
@rvagg I'm wondering why node doesn't use the `RTLD_LOCAL` flag for `dlopen()` by default? In my testing (of `leveldown` on mac) that fixed an overlap of symbols, to the same effect as `-fvisibility=hidden`.

**Comment by rvagg** [comment]
I don't know, historical I suppose, and changing these things is tricky since it has so much breaking potential. But maybe that could be done in a semver-major in Node. @bnoordhuis I'm sure you understand this way better than I, thoughts?

**Comment by vweevers** [comment]
Some data: https://github.com/vweevers/about-native-modules

**Comment by rvagg** [comment]
To get some discussion going, maybe try opening a PR against nodejs/node to actually make the change? You'll get a lot of folks coming out of the woodwork with opinions if you did that I reckon.

**Comment by vweevers** [comment]
I've surveyed a bunch of native addons and only found real issues in `leveldown` and `rocksdb` so far, apart from unrelated issues with shared libraries. So I don't have a strong case for changing node behavior. I'll continue to survey addons, improving my understanding of the issue along the way.

**Comment by rvagg** [comment]
sooooo I'm not seeing a path to reintroducing this without coordination between node-gyp, npm and node.js to make sure it lands semver-major in each of them. I just don't see that happening.
