### ISSUE TITLE
ares.h missing from iojs node-gyp

### ISSUE THREAD

**Issue by tolmasky** [nodejs/node-gyp#638]
#include "string_bytes.h" works fine in 0.12, but gives this error in iojs:

src/env.h:4:10: fatal error: 'ares.h' file not found
#include "ares.h"

env.h includes ares.h, but it seems node-gyp does not include ares.h.

**Comment by TooTallNate** [comment]
Try deleting the `~/.node-gyp` dir and installing again. You probably got a bad untar somehow (rare, but seems to happen unfortunately).

**Comment by Fishrock123** [comment]
@tolmasky let us know if you still have this issue. :)
