### ISSUE TITLE
Unable to include tree.h in some of the node versions.

### ISSUE THREAD

**Issue by royalpinto** [nodejs/node-gyp#993]
Hi,

Unable to include `tree.h` header in some of the `node` versions and build is failing.

Works with these versions: `0.9.3, 0.9.12, 0.10.0, 0.10.10, 4.3.0, 4.3.1`
Doesn't work with versions: `0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.10.45`

Error on Linux:
```
../src/cares_wrap.cc:30:18: fatal error: tree.h: No such file or directory
#include "tree.h"
```
Error on MacOS:
```
In file included from ../src/cares_wrap.cc:30:
In file included from /usr/include/c++/4.2.1/backward/tree.h:47:
/usr/include/c++/4.2.1/backward/backward_warning.h:32:2: warning: This file includes at least one deprecated or antiquated header. Please consider using one of the 32 headers
      found in section 17.4.1.2 of the C++ standard. Examples include substituting the <X> header for the <X.h> header for C++ includes, or <iostream> instead of the deprecated
      header <iostream.h>. To disable this warning use -Wno-deprecated. [-W#warnings]
#warning This file includes at least one deprecated or antiquated header. \
 ^
../src/cares_wrap.cc:116:7: error: unknown type name 'RB_ENTRY'
      RB_ENTRY(ares_task_t) node;
      ^
.
.
.
```

Quick find resulted into this (`find . | grep /tree.h`):
```
royalpinto@ubuntu:~/.node-gyp$ find . | grep /tree.h | sort
./0.10.0/deps/uv/include/uv-private/tree.h
./0.10.0/src/tree.h
./0.10.10/deps/uv/include/uv-private/tree.h
./0.10.10/src/tree.h
./0.10.30/deps/uv/include/uv-private/tree.h
./0.10.30/src/tree.h
./0.10.45/include/node/uv-private/tree.h
./0.12.0/deps/uv/include/tree.h
./0.12.0/src/tree.h
./0.8.0/deps/uv/include/uv-private/tree.h
./0.8.1/deps/uv/include/uv-private/tree.h
./0.8.2/deps/uv/include/uv-private/tree.h
./0.8.3/deps/uv/include/uv-private/tree.h
./0.8.4/deps/uv/include/uv-private/tree.h
./0.8.5/deps/uv/include/uv-private/tree.h
./0.9.0/deps/uv/include/uv-private/tree.h
./0.9.12/deps/uv/include/uv-private/tree.h
./0.9.12/src/tree.h
./0.9.3/deps/uv/include/uv-private/tree.h
./0.9.3/src/tree.h
./4.3.0/include/node/tree.h
./4.3.1/include/node/tree.h
royalpinto@ubuntu:~/.node-gyp$
```

Seems like the versions were it's not working has only one `tree.h` header file within `uv-private/`, but working versions has `tree.h` within `src/` as well.

What could be wrong here. Is it safe to use `tree.h` from `node` or it has to be maintained in the project ?

Thanks

**Comment by rvagg** [comment]
Setting aside the unsupported versions (< v0.10), we can see the following in the headers tarball which is what the majority of users will be using to compile addons:

```
$ curl -sL https://nodejs.org/download/release/v0.10.46/node-v0.10.46-headers.tar.xz | tar Jtv | grep tree.h
-rw-r--r--  0 iojs   staff   52889 24 Jun 01:17 node-v0.10.46/include/node/uv-private/tree.h
$ curl -sL https://nodejs.org/download/release/v0.12.15/node-v0.12.15-headers.tar.xz | tar Jtv | grep tree.h
-rw-r--r--  0 iojs   staff   52889 24 Jun 02:48 node-v0.12.15/include/node/tree.h
$ curl -sL https://nodejs.org/download/release/v4.4.7/node-v4.4.7-headers.tar.xz | tar Jtv | grep tree.h
-rw-r--r--  0 iojs   staff   52889 24 Jun 02:48 node-v4.4.7/include/node/tree.h
$ curl -sL https://nodejs.org/download/release/v6.3.0/node-v6.3.0-headers.tar.xz | tar Jtv  | grep tree.h
-rw-r--r--  0 iojs   staff   52889 24 Jun 02:48 node-v6.3.0/include/node/tree.h
```

Looks like we have a problem with consistency in v0.10, unsure yet what the reason for that is but it might be something we need to fix because src/tree.h isn't new.

**Comment by rvagg** [comment]
OK, so the reason for the above inconsistency is simply that tree.h is coming in from libuv and in the version we ship in v0.10 it's in uv/include/uv-private/tree.h but from v0.12 and onward it's in uv/include/tree.h, hence the location discrepancy.

The additional discrepancy you're seeing in your research above is that in v0.10.x from v0.10.41 and later, in v0.12.x from v0.12.10 and later, and in all versions later than v4.0.0, we're shipping header tarballs which node-gyp will download by default. These don't contain the src/tree.h that you're seeing above as that's only in the full source tarball download (you're not seeing it in v0.8 because I believe tree.h wasn't in src/ in v0.8). The vast majority of users will get the headers tarball but if you use `--nodedir` to point to a node source directory, you can still get src/tree.h (and I think maybe some other situations but they should be rare).

I suggest what you could probably do is macro branch on `UV_VERSION_MAJOR`, if it's < 1 then it'll (probably) be "uv-private/tree.h", >= 1 it'll be just "tree.h". Or you could just drop support for v0.10 and be done with it since it's going to be EOL in October. Your call.

**Comment by bnoordhuis** [comment]
> Is it safe to use tree.h from node or it has to be maintained in the project ?

The latter, tree.h is an internal header / implementation detail.  There are really only four headers intended for public consumption in the src/ directory: node.h, node_version.h, node_buffer.h and node_object_wrap.h.

Consult tools/install.py when in doubt, it's effectively the canonical source: https://github.com/nodejs/node/blob/v6.3.0/tools/install.py#L146-153

**Comment by rvagg** [comment]
@bnoordhuis `subdir_files('deps/uv/include', 'include/node/', action)` means we ship it as if it's ours, we basically own it as far as addon authors need be concerned.

**Comment by bnoordhuis** [comment]
There are two copies of tree.h, one in deps/uv/include and one in src/.  It's the second one that @royalpinto is having issues with.

Using the other is not a great idea because while they are the same now, there is no reason they can't diverge.  Simplest and robustest solution is to simply copy over the header.

**Comment by royalpinto** [comment]
Hi @rvagg @bnoordhuis,

Thanks for detailed information and suggestions. Looks like `tree.h` is same through out all `node` versions from 0.8.0 till the latest 6.3.0. I think copying over the header would be a simplest and robustest solution as suggested by @bnoordhuis. (Doesn't have to maintain multiple versions either, as its same everywhere). This way it should work for all the versions without additional changes.

Thanks a lot!
