### ISSUE TITLE
node-gyp rebuild error on Raspbian Jessie

### ISSUE THREAD

**Issue by 7rncs** [nodejs/node-gyp#1329]
* **Node Version**:  Node Versions: 4.8.6, 6.12.0, 8.9.0 and 9.1.0 - NPM: 2.15.11, 3.X and 5.5.1
* **Platform**:  Raspbian Jessie, Linux Kernel 4.9.35
* **Module**: Airtunes (https://github.com/lperrin/node_airtunes) and alsa (https://www.npmjs.com/package/alsa)

Hello everyone,
running into big problems with node-gyp. I tried to install two modules (ref. above) and both are practically throwing the same problem with node-gyp. I have tried multiple Node and NPM versions with NVM, without NVM. I have reinstalled node-gyp. I have tried to set path variables for node-gyp. I have tweaked user permissions. However I have found no solution. I really need some expert insight as I am a beginner with node.js

Further information: Other node modules are working flawless, it seems to be an issue with building those two modules with node-gyp. Also the module node_airtunes works without a problem if I install it via another module called node-airplayhub (https://github.com/noelhibbard/node-airplayhub). Also, I remember that I had node_airtunes running on a older version of my Raspberry maybe 1-2 years ago, I think it was Raspbian Wheezy. Maybe these info might help you.

I would really really appreciate your help as I have searched and tried all suggestions that can be found on the web, this is my last hope!

<details><summary>Log output (from npm or node-gyp):</summary>

```
(Module alsa - Only the last part of the Log, please let me know whether you need more)
alsa.target.mk:92: recipe for target 'Release/obj.target/alsa/alsa.o' failed
make: *** [Release/obj.target/alsa/alsa.o] Error 1
make: Leaving directory '/home/pi/Node-Projekt/node_modules/alsa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v9.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v9.1.0/bin/node" "/home/pi/.nvm/versions/node/v9.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Node-Projekt/node_modules/alsa
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/Node-Projekt/package.json'
npm WARN Node-Projekt No description
npm WARN Node-Projekt No repository field.
npm WARN Node-Projekt No README data
npm WARN Node-Projekt No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alsa@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alsa@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-11-07T23_07_15_100Z-debug.log

(Module airtunes - Only the last part of the Log, please let me know whether you need more)
airtunes.target.mk:101: recipe for target 'Release/obj.target/airtunes/src/codec.o' failed
make: *** [Release/obj.target/airtunes/src/codec.o] Error 1
make: Leaving directory '/home/pi/Node-Projekt/node_modules/airtunes/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v9.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v9.1.0/bin/node" "/home/pi/.nvm/versions/node/v9.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Node-Projekt/node_modules/airtunes
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/Node-Projekt/package.json'
npm WARN Node-Projekt No description
npm WARN Node-Projekt No repository field.
npm WARN Node-Projekt No README data
npm WARN Node-Projekt No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airtunes@0.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the airtunes@0.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-11-07T23_06_11_248Z-debug.log
```

</details>

**Comment by bnoordhuis** [comment]
The actual build error is missing (probably further up) but it looks like an issue with the add-ons you're trying to build, not node-gyp itself.

**Comment by 7rncs** [comment]
Here is the rest of the log, can you spot anything? This is a fresh Raspbian Jessie install... :

> alsa@0.0.2 install /home/pi/Node-Projekt/node_modules/alsa
> node-gyp rebuild

make: Entering directory '/home/pi/Node-Projekt/node_modules/alsa/build'
  CXX(target) Release/obj.target/alsa/alsa.o
In file included from ../alsa.cc:3:0:
../pcm.h:16:31: error: expected class-name before ‘{’ token
 class Pcm : public ObjectWrap {
                               ^
../pcm.h:48:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../pcm.h:100:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../pcm.h:101:35: error: ‘Arguments’ does not name a type
   static Handle<Value> Open(const Arguments& args);
                                   ^
../pcm.h:102:36: error: ‘Arguments’ does not name a type
   static Handle<Value> Close(const Arguments& args);
                                    ^
../pcm.h:103:35: error: ‘Arguments’ does not name a type
   static Handle<Value> Read(const Arguments& args);
                                   ^
../pcm.h:104:36: error: ‘Arguments’ does not name a type
   static Handle<Value> Write(const Arguments& args);
                                    ^
../pcm.h:106:62: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> OpenedGetter(Local<String> str, const AccessorInfo& accessor);
                                                              ^
../pcm.h:107:64: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> ReadableGetter(Local<String> str, const AccessorInfo& accessor);
                                                                ^
../pcm.h:108:64: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> WritableGetter(Local<String> str, const AccessorInfo& accessor);
                                                                ^
../pcm.h:111:22: error: ‘uv_work_t’ has not been declared
   static void DoRead(uv_work_t* req);
                      ^
../pcm.h:112:25: error: ‘uv_work_t’ has not been declared
   static void AfterRead(uv_work_t* req);
                         ^
../pcm.h:115:23: error: ‘uv_work_t’ has not been declared
   static void DoClose(uv_work_t* req);
                       ^
../pcm.h:116:26: error: ‘uv_work_t’ has not been declared
   static void AfterClose(uv_work_t* req);
                          ^
../pcm.h:119:23: error: ‘uv_work_t’ has not been declared
   static void DoWrite(uv_work_t* req);
                       ^
../pcm.h:120:26: error: ‘uv_work_t’ has not been declared
   static void AfterWrite(uv_work_t* req);
                          ^
../pcm.h: In constructor ‘alsa::Pcm::Pcm()’:
../pcm.h:21:11: error: class ‘alsa::Pcm’ does not have any field named ‘ObjectWrap’
   Pcm() : ObjectWrap(),
           ^
../pcm.h: In constructor ‘alsa::Pcm::Baton::Baton(alsa::Pcm*, v8::Handle<v8::Function>)’:
../pcm.h:54:12: error: ‘class alsa::Pcm’ has no member named ‘Ref’
       pcm->Ref();
            ^
../pcm.h:55:7: error: ‘request’ was not declared in this scope
       request.data = this;
       ^
../pcm.h:56:47: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Handle<v8::Function>&)’
       callback = Persistent<Function>::New(cb_);
                                               ^
../pcm.h:56:47: note: candidate is:
In file included from /home/pi/.node-gyp/9.1.0/include/node/node.h:63:0,
                 from ../alsa.cc:1:
/home/pi/.node-gyp/9.1.0/include/node/v8.h:9201:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/pi/.node-gyp/9.1.0/include/node/v8.h:9201:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../alsa.cc:3:0:
../pcm.h: In destructor ‘virtual alsa::Pcm::Baton::~Baton()’:
../pcm.h:59:12: error: ‘class alsa::Pcm’ has no member named ‘Unref’
       pcm->Unref();
            ^
../pcm.h:60:16: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
       callback.Dispose();
                ^
alsa.target.mk:92: recipe for target 'Release/obj.target/alsa/alsa.o' failed
make: *** [Release/obj.target/alsa/alsa.o] Error 1
make: Leaving directory '/home/pi/Node-Projekt/node_modules/alsa/build'
gyp ERR! build error

**Comment by bnoordhuis** [comment]
That module was written for an old version of node.js.  https://www.npmjs.com/package/alsa tells me the last release was in 2013 so that means it's bitrotted.

**Comment by 7rncs** [comment]
So what does this mean? I need to use a specific version of node.js?

**Comment by bnoordhuis** [comment]
Or another module that works with newer versions.

**Comment by 7rncs** [comment]
How can I check which version is supported? Unfortunately there is no indication in the package.json...

**Comment by bnoordhuis** [comment]
Trial and error, basically.  Going by the build errors, I'd say it was written for v0.10.

**Comment by 7rncs** [comment]
Incredible ... it worked with v0.10. Thanks!
